version: '3.8'

services:
  ft-transfer-api:
    image: ${DOCKER_REGISTRY}/ft-transfer-api:${APP_VERSION:-latest}
    container_name: ft-transfer-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NETWORK_ID=${NETWORK_ID:-testnet}
      - NODE_URL=${NODE_URL:-https://rpc.testnet.near.org}
      - MASTER_ACCOUNT_ID=${MASTER_ACCOUNT_ID}
      - MASTER_PRIVATE_KEY=${MASTER_PRIVATE_KEY}
      - CONTRACT_ID=${CONTRACT_ID}
      - BATCH_SIZE=${BATCH_SIZE:-10}
      - BATCH_INTERVAL_MS=${BATCH_INTERVAL_MS:-1000}
      - KEY_ROTATION_COUNT=${KEY_ROTATION_COUNT:-10}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: ft-transfer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.23-alpine
    container_name: ft-transfer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ft-transfer-api
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
    driver: local